# Generated by Django 4.2.4 on 2023-08-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pics/%y/%m/%d/")),
                ("title", models.CharField(max_length=50)),
                ("sub_title", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="About",),
        migrations.DeleteModel(name="Client",),
        migrations.DeleteModel(name="RecentWork",),
        migrations.DeleteModel(name="Service",),
    ]
